[package]
name = "play_tune"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
"opl3-rs" = { path = "../.." }
"rodio" = "0.19"
"chrono" = "0.4"
"timer" = "0.2"
"crossbeam-channel" = "0.5"
"hound" = "3.5"
"bpaf" = { version = "0.9", features = ["autocomplete"] }